services:
  db:
    container_name: db
    image: postgres:14-alpine
    networks:
      - todo-app-net
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: app
      POSTGRES_DB: todo-web-app
    ports:
      # Mapped to 8080 instead of 5432 because we somehow cannot connect from host if container use default port
      - 8080:5432

networks:
  todo-app-net: {}
