services:
  ui:
    build:
      context: .
    networks:
      - todo-app-net
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      PORT: 80
      NEXTAUTH_SECRET: 9DFu4723hsgiiyogsf732fglhsfgjTDFGFofdvbbsdlfbkvtKLGKJfgjn74djf
      NEXTAUTH_URL: "http://localhost/"
      DATABASE_URL: "postgresql://app:123@db/todo-web-app?schema=public&connection_limit=5"

  db:
    image: postgres:14-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - todo-app-net
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: app
      POSTGRES_DB: todo-web-app
      


networks:
  todo-app-net: {}

volumes:
  postgres-volume: 
    




